# Generated by Django 4.2.16 on 2024-11-24 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=255)),
                ('performance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CardOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('option_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.optioncategory')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='card_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardcategory'),
        ),
        migrations.AddField(
            model_name='card',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.company'),
        ),
    ]
