# Generated by Django 4.2.16 on 2024-11-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helparticle',
            name='help_category',
            field=models.CharField(choices=[('HELP', '도와줘요'), ('RECOM', '추천해요'), ('TOGETHER', '함께해요')], default='HELP', max_length=255, verbose_name='질문 카테고리'),
            preserve_default=False,
        ),
    ]
